#pragma once

#define IDI_APP_ICON 101
#define IDR_TIGA_CHEST_REFERENCE_PNG 201
#define IDR_TIGA_CHEST_WARNING_ON_PNG 202
#define IDR_TIGA_CHEST_WARNING_OFF_PNG 203
#define IDR_TIGA_CHEST_STONE_PNG 204
